close all;
clc;
addpath('src'); 
addpath('util');
addpath('util/ojwoodford-export_fig-5735e6d/');

% For MPI, mode = 2. For COCO, mode = 1.
mode = 1;
param = config(mode);
model = param.model(param.modelID);
net = caffe.Net(model.deployFile, model.caffemodel, 'test');
 cat_dict={...
 {'applauding',			284},...
 {'blowing_bubbles',			259},...
 {'brushing_teeth',			200},...
 {'cleaning_the_floor',		212},...
 {'climbing',			295},...
 {'cooking',				288},...
 {'cutting_trees',			203},...
 {'cutting_vegetables',		189},...
 {'drinking',			256},...
 {'feeding_a_horse',			287},...
 {'fishing',				273},...
 {'fixing_a_bike',			228},...
 {'fixing_a_car',			251},...
 {'gardening',			199},...
 {'holding_an_umbrella',		292},...
 {'jumping',				295},...
 {'looking_through_a_microscope',	191},...	
 {'looking_through_a_telescope',	203},...
 {'playing_guitar',			289},...
 {'playing_violin',			260},...
 {'pouring_liquid',			200},...
 {'pushing_a_cart',			235},...
 {'reading',				245},...
 {'phoning',				259},...
 {'riding_a_bike',			293},...
 {'riding_a_horse',			296},...
 {'rowing_a_boat',			185},...
 {'running',				251},...
 {'shooting_an_arrow',		214},...
 {'smoking',				241},...
 {'taking_photos',			197},...
 {'texting_message',			193},...
 {'throwing_frisby',			202},...
 {'using_a_computer',		230},...
 {'walking_the_dog',			293},...
 {'washing_dishes',			182},...
 {'watching_TV',			223},...
 {'waving_hands',			210},...
 {'writing_on_a_board',		183},...
 {'writing_on_a_book',		246}};

close all;
%savePath = 'result_stanford40_trainval';
savePath = '/media/hci-jw/Plextor1tb/workspace/data/PartImages/';
for i=1:length(cat_dict)
    cat_name = cat_dict{i}{1};
    cat_num = cat_dict{i}{2};
    pics = dir(['/media/hci-jw/Plextor1tb/workspace/data/BBoxImage/' cat_name '_train']);
    pics = pics(3:end);
    cat_num = length(pics)
    
    ff=fopen([savePath cat_name '_train']);
    if(ff==-1)
        mkdir([savePath cat_name '_train']);
    end
    for m = 1:cat_num
        im_name = pics(m).name;
        disp(im_name);

        oriImg = imread(['/media/hci-jw/Plextor1tb/workspace/data/BBoxImage/' cat_name '_train/' im_name]);
        if(size(oriImg,2)/2>size(oriImg,1))
             scale0 = 368/max(size(oriImg, 2));
        else
            scale0 = 368/max(size(oriImg, 1));
        end
        %scale0 = 368/size(oriImg, 1);
        twoLevel = 1;
        [final_score, ~] = applyModel(oriImg, param, net, scale0, 1, 1, 0, twoLevel);
        vis = 0;

        if mode == 1
            [candidates, subset] = connect56LineVec(oriImg, final_score, param, vis);
        elseif mode == 2
            [candidates, subset] = connect43LineVec(oriImg, final_score, param, vis);
        end

        boxes = genBbox(oriImg, candidates,subset,hsv(7),vis);
        parts={'head', 'torso', 'legs', 'larm', 'rarm', 'lhand', 'rhand'};
        for j=1:length(parts)
            if(isfield(boxes,parts{j}))
                bbox=getfield(boxes,parts{j});
                patch=oriImg(bbox(2):bbox(4),bbox(1):bbox(3),:);
                resized_patch = imresize(patch, [224 224]);
                imwrite(resized_patch, [savePath cat_name '_train/' im_name(1:end-4) '_' num2str(j) parts{j} '.jpg'], 'jpg');
                %id=id+1;
            else
                patch = im2uint8(zeros(224,224,3)) +128;
                imwrite(patch, [savePath cat_name '_train/' im_name(1:end-4) '_' num2str(j) parts{j} '.jpg'], 'jpg');
            end
            
        end
    end
end   
%     a = lines();
%     boxes = genBbox(oriImg, candidates,subset,a(10:end,:),vis);
%     
%     if(~exist(fullfile(savePath, cat_name))) mkdir(fullfile(savePath, cat_name)); end
%     %save([fullfile(savePath,cat_name), '/' im_name(1:end-4) '.mat'],'boxes');
%     end
%end
